### ISSUE TITLE
Unsoundness: This crate permits constructing invalid instances of enums

### ISSUE THREAD

**Issue by saethlin** [mokeyish/enum-flags#1]
I built this example based on the test called `test_bitand`:
```rust
fn main() {
    #[derive(enum_flags::EnumFlags, Copy, Clone, PartialEq)]
    enum State {
        None = 0,
        A = 1,
        B = 2,
        C = 4,
    }

    let s: State = State::A | State::B;
    println!("{}", match s {
        State::None => "None",
        State::A => "A",
        State::B => "B",
        State::C => "C",
    });
}
```
Which prints:
```
$ cargo run
   Compiling scratch v0.1.0 (/tmp/scratch)
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/scratch`
Illegal instruction (core dumped)
```
The instance `s` is not a valid `State`. Its discriminant has a value of `0x3`. So any attempt to match on it sends program execution flying off who-knows-where, thus constructing an invalid enum is UB.

I found this by running `cargo +nightly miri test` in the latest version of this crate.

**Comment by mokeyish** [comment]
The `s` actually is 3 in memory. but 3 is not declared in enum `state`，so you should't use it with `match`.  It's not problem with the version of rust.

**Comment by saethlin** [comment]
> The `s` actually is 3 in memory. but 3 is not declared in enum `state`

Rust enums are not C enums. They're not just a name for a few constants, Rust enums are a type with perhaps nuanced validity requirements. Breaking those requirements is UB. My example of using `match` just explains how this UB quickly goes wrong in a very obvious way, but Miri detects this UB upon the creation of the new enum from an integer value, on this line: https://github.com/mokeyish/enum-flags/blob/3bf1827ba960e9ef50c7375d0f2cbbe021cc16f4/src/lib.rs#L119

> so you should't use it with `match`

That's not how Rust works. Safe code must not be able to produce UB (as is happening in this example), and it is the responsibility of users of `unsafe` to prevent that possibility.

The problem is not with the use of `match`, which is safe code. The problem is in the usage of `unsafe` to construct an invalid instance of this type.

**Comment by mokeyish** [comment]
I've not idea about using `match` with `enum-flags`. you should use 
```rust
let a = State::A | State::B;
if a.has_flag(State::A)  or  a.contains(State::A)  {
    // do some stuff
} else if a.has_b() {
    // do some stuff
} else if a.is_empty() {
    // do some stuff
} else if a.is_all() {
    // do some stuff
}
```
instead.

**Comment by SabrinaJewson** [comment]
The problem manifests without `match` too. For example, this code prints out `None`:

```rs
use enum_flags::EnumFlags;

#[derive(PartialEq, Clone, Copy, EnumFlags)]
enum Foo {
    A = 1,
    B = 2,
}

fn main() {
    println!("{:?}", Some(Foo::from_num(0)));
}
```

as does this code:

```rs
use enum_flags::EnumFlags;

#[derive(PartialEq, Clone, Copy, EnumFlags)]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
}

fn main() {
    println!("{:?}", Some(Foo::A | Foo::B));
}
```

In the Rust reference's list of [behaviour considered undefined](https://doc.rust-lang.org/reference/behavior-considered-undefined.html), it explicitly states that the following is considered UB:

> Producing an invalid value, even in private fields and locals. "Producing" a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation. The following values are invalid (at their respective type):
> * A discriminant in an `enum` not included in the type definition.

**Comment by mokeyish** [comment]
Maybe I should produce the `combined` enum fields.  such as:
```rust
#[derive(PartialEq, Clone, Copy, EnumFlags)]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
}
```

will produce the code as follow:
```rust
#[derive(PartialEq, Clone, Copy, EnumFlags)]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
   __A_and_B__=3
}
```

Anyone knowns how to append enums field with rust macros?

**Comment by saethlin** [comment]
You can't add just one or two more fields to get out of this situation. `|` is not the only operation that can be used to construct an invalid variant.

Given just this enum, I can (invalidly) construct any variant value I want:
```rust
#[derive(EnumFlags, Copy, Clone, PartialEq)]
enum State {
    None = 0,
    A = 1,
}
```
I can do `!State::None` to get `0xff` then repeatedly subtract `State::A` from it, producing any value in the range of the discriminant.

IMO the whole idea of this crate is that you can use an enum like an integer, and that's fundamentally wrong in Rust. The right tool here is [`bitflags`](https://crates.io/crates/bitflags). If you want to support bit-operations between instances, adding almost any useful functionality will permit constructing invalid instances of the flags type. Modeling this with a struct instead of an enum gets rid of this problem.

**Comment by mokeyish** [comment]
`!State::None` can fallback to `State::A | State::B | State::C | ...`, but not `0xff`.

**Comment by saethlin** [comment]
I think you keep misunderstanding me. The problem is not these specific examples, the problem is that you can't do arithmetic with arbitrary enum variants, retain any reasonable meaning of those arithmetic operations, and also stay within the domain of the arbitrary variants in the enum. The _design_ of this crate isn't sound, this isn't an issue of an implementation detail.

**Comment by mokeyish** [comment]
I used [bitflags](https://crates.io/crates/bitflags) before, but I don't like it. Enumflag in CSharp is really good, I just wan't bring it to Rust.

I found another way to avoid Unsoundness.

```rust
#[derive(PartialEq, Clone, Copy, EnumFlags)]
#[repr(u32)]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
}
```

will produce the code as follow:
```rust
#[derive(PartialEq, Clone, Copy, EnumFlags)]
#[repr(u32)]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
   __Composed__(u32)= 0xff   // other value store here.
}
```

https://doc.rust-lang.org/beta/unstable-book/language-features/arbitrary-enum-discriminant.html

**Comment by mokeyish** [comment]
@saethlin @SabrinaJewson Hello, this issue has been solved in version  [0.3.0-preview](https://crates.io/crates/enum-flags/0.3.0-preview).

```rust
#![feature(arbitrary_enum_discriminant)]
use enum_flags::enum_flags;

#[repr(u8)]
#[enum_flags]
#[derive(Copy, Clone, PartialEq)]
enum Flags{
    None = 0,
    A = 1,
    B = 2,
    C = 4
}
fn main() {
    let e1: Flags = Flags::A | Flags::C;
    let e2 = Flags::B | Flags::C;

    assert_eq!(e1 | e2, Flags::A | Flags::B | Flags::C); // union
    assert_eq!(e1 & e2, Flags::C); // intersection
    assert_eq!(e1 ^ e2, Flags::A | Flags::B); // toggle
    assert_eq!(e1 & (!Flags::C), Flags::A); // deletion
    assert_eq!(e1 - Flags::C, Flags::A); // deletion

    assert_eq!(format!("{:?}", e1).as_str(), "(Flags::A | Flags::C)");
    assert!(e1.has_a());
    assert!(!e1.has_b());
    assert!(e1.has_flag(Flags::C));
    assert!(e1.contains(Flags::C));
    assert_eq!(match Flags::A | Flags::C {
        Flags::None => "None",
        Flags::A => "A",
        Flags::B => "B",
        Flags::C => "C",
        Flags::__Composed__(v) if v == Flags::A | Flags::B => "A and B",
        Flags::__Composed__(v) if v == Flags::A | Flags::C => "A and C",
        _ => "Others"
    }, "A and C")
}
```
BTW， would you have better name for `__Composed__` ？

**Comment by saethlin** [comment]
The new version fails Miri as well, for a different reason:
```
test test_bitand ... error: Undefined Behavior: memory access failed: alloc67390 has size 8, so pointer to 16 bytes starting at offset 0 is out-of-bounds
   --> /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:701:9
    |
701 |         copy_nonoverlapping(src, tmp.as_mut_ptr(), 1);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ memory access failed: alloc67390 has size 8, so pointer to 16 bytes starting at offset 0 is out-of-bounds
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
            
    = note: inside `std::ptr::read::<test_bitand::State>` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:701:9
note: inside `<test_bitand::State as std::convert::From<usize>>::from` at tests/test_flags.rs:83:5
   --> tests/test_flags.rs:83:5
    |
83  |     #[enum_flags]
    |     ^^^^^^^^^^^^^
note: inside `<test_bitand::State as std::ops::BitAnd>::bitand` at tests/test_flags.rs:83:5
   --> tests/test_flags.rs:83:5
    |
83  |     #[enum_flags]
    |     ^^^^^^^^^^^^^
note: inside `test_bitand` at tests/test_flags.rs:93:13
   --> tests/test_flags.rs:93:13
    |
93  |     let s = s & State::C;
    |             ^^^^^^^^^^^^
note: inside closure at tests/test_flags.rs:81:1
   --> tests/test_flags.rs:81:1
    |
80  |   #[test]
    |   ------- in this procedural macro expansion
81  | / fn test_bitand(){
82  | |
83  | |     #[enum_flags]
84  | |     #[derive(Copy, Clone, PartialEq)]
...   |
94  | |     assert_eq!(State::None, s);
95  | | }
    | |_^
    = note: this error originates in the attribute macro `enum_flags` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I think the problem here is that adding this `__Composed__` field grows the size of the enum, because it needs to have at least one other byte for the discriminant. If you want to go with this design, the reference has some suggestions on juggling the layout of enums with fields: https://doc.rust-lang.org/reference/type-layout.html#reprc-enums-with-fields

I mentioned this crate on the community Discord, and got an interesting suggestion: In the proc macro, you could track all the possible values that this enum can have, then when you go to construct a new instance of it in one of the operations, you could check if the new instance would be valid and panic if it won't be.

**Comment by mokeyish** [comment]
Do you switch to nightly channel?  and add `#![feature(arbitrary_enum_discriminant)]`，I used the feature in nightly channel.

**Comment by saethlin** [comment]
Yes. Miri is nightly-only.

**Comment by mokeyish** [comment]
Sorry I know few about miri, What's the difference between miri and normal rust library? I have  tested it in my local envronment.

**Comment by saethlin** [comment]
Miri is an interpreter for Rust which checks many of the normally-unchecked rules you need to follow when writing unsafe code. It's available as a rustup component, so on a nightly toolchain you can `rustup component add miri`. Then in any project you can `cargo miri run` or `cargo miri test`.

There is a more complete description of it in the repo's README: https://github.com/rust-lang/miri

**Comment by mokeyish** [comment]
Thanks, I seem to find that the error is caused by this lines:

https://github.com/mokeyish/enum-flags/blob/a41d01b3bde586ea7fcaeab72f504c310fa04479/src/lib.rs#L163-L166

To cast int-type to Enum.  This should be solvable.

**Comment by mokeyish** [comment]
@saethlin Hi, errors in miri have been solved in version [0.3.0-preview2](https://crates.io/crates/enum-flags/0.3.0-preview2)

**Comment by rodrimati1992** [comment]
The macro doesn't seem to be usable.

# First error

The proc macro panics with this code
```rust
use enum_flags::enum_flags;

#[repr(u8)]
#[enum_flags]
#[derive(Copy, Clone, PartialEq)]
enum Flags{
    None,
    A,
    B,
    C,
}
```
```
error: custom attribute panicked
 --> src/main.rs:4:1
  |
4 | #[enum_flags]
  | ^^^^^^^^^^^^^
  |
  = help: message: called `Option::unwrap()` on a `None` value
```

# Second error

When I set the discriminants like so:
```rust
use enum_flags::enum_flags;

#[repr(u8)]
#[enum_flags]
#[derive(Copy, Clone, PartialEq)]
enum Flags{
    None = 0,
    A = 1,
    B = 2,
    C = 3,
}

```
it gives me this error
```
error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants
  --> src/lib.rs:7:12
   |
4  | #[enum_flags]
   | ------------- tuple variant defined here
...
7  |     None = 0,
   |            ^ disallowed custom discriminant
8  |     A = 1,
   |         ^ disallowed custom discriminant
9  |     B = 2,
   |         ^ disallowed custom discriminant
10 |     C = 3,
   |         ^ disallowed custom discriminant
   |
   = note: see issue #60553 <https://github.com/rust-lang/rust/issues/60553> for more information
   = help: add `#![feature(arbitrary_enum_discriminant)]` to the crate attributes to enable
```
> Since use feature `arbitrary_enum_discriminant`, nightly channel is required.

Hmm, never mind the second error. You only support the nightly channel .

I don't plan to use this library (I don't see a bitflags alternative to be nightly-worthy), I'm just reporting errors I got from naïve uses of this library.

**Comment by mokeyish** [comment]
@rodrimati1992 Yes，I use the  feature `arbitrary_enum_discriminant`,  It's a feature that only exist in nightly channel now.
You must  add`#![feature(arbitrary_enum_discriminant)]` to enable this feature.

**Comment by mokeyish** [comment]
@rodrimati1992 Hello. For the first error, I just add hints right now in version [0.3.0-preview3](https://crates.io/crates/enum-flags/0.3.0-preview3)

<img width="1101" alt="图片" src="https://user-images.githubusercontent.com/16131917/155452675-b314c5d9-4941-49bf-af8a-9c6c6e5415cc.png">

**Comment by mokeyish** [comment]
@rodrimati1992   Hi， The first error has also been fixed.

```rust
#[repr(u8)]  // default: #[repr(usize)]
#[enum_flags]
#[derive(Copy, Clone, PartialEq)] // can be omitted
enum Flags{
    None = 0,
    A = 1,
    B, // 2
    C = 4
}
```

**Comment by mokeyish** [comment]
@saethlin Hi. All errors above have been fixed.  Do you have any other questions?

**Comment by saethlin** [comment]
Nope! I can't find any other problems here. The implementation you came up with is quite clever :+1: .

**Comment by mokeyish** [comment]
Thank you for your feedback
