### ISSUE TITLE
Unoptimal in-memory size

### ISSUE THREAD

**Issue by meithecatte** [mokeyish/enum-flags#2]
Consider the example in the readme.

```
    println!("{}", std::mem::size_of::<Flags>());
```

prints `2`, even though the representation used is a `u8`. Since bitflags are often used when memory usage is a concern, I'd call this a bug.

**Comment by mokeyish** [comment]
The memory usage depends on `repr(int-type)`.
- When`#[repr(u8)]`,  the `size_of::<Flags>()` will be 2.
- When `#[repr(u16)]`,  the `size_of::<Flags>()` will be 4.

**Comment by meithecatte** [comment]
Yes. However a `#[repr(u8)]` bitflag can hold eight flags, which should
fit in a size of 1.

**Comment by mokeyish** [comment]
The implementation before version 0.30 of [enum-flags](https://github.com/mokeyish/enum-flags)  is 1. When using it with `match` will cause UB problem. So I made this implementation  now.
e.g.:
```rust
#[repr(u8)]
#[enum_flags]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
}
```

will produce the code as follow:
```rust
#[repr(u8)]
#[enum_flags]
enum Foo {
    None = 0,
    A = 1,
    B = 2,
   __Composed__(u8)   // other value stores here.
}
```

and use it witch `match`

```rust
    assert_eq!(match Flags::A | Flags::C {
        Flags::None => "None",
        Flags::A => "A",
        Flags::B => "B",
        Flags::C => "C",
        Flags::__Composed__(v) if v == Flags::A | Flags::B => "A and B",
        Flags::__Composed__(v) if v == Flags::A | Flags::C => "A and C",
        _ => "Others"
    }, "A and C")
```

**Comment by meithecatte** [comment]
Hi, I was curious how you fixed this, but I couldn't find the commit. Could you link me to it?

**Comment by mokeyish** [comment]
I store other values at `Enum::__Composed__(v)`

**Comment by meithecatte** [comment]
Okay, but that still has the issue of taking 2 times as much memory as needed for the data, no?

**Comment by mokeyish** [comment]
Yes
